### ISSUE TITLE
Cache Windows installations

### ISSUE THREAD

**Issue by Piedone** [ankane/setup-sqlserver#3]
It takes about 5 minutes to set up SQL Server 2019 on a GitHub-hosted latest Windows runner. Perhaps some of this time can be saved with [caching](https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows)
?

Related info about caching Docker images, since that might be a similar scenario:

- [Cache pulled docker images (already built and published)](https://github.community/t/cache-pulled-docker-images-already-built-and-published/17753/6) 
- [Docker caching · Issue #31 · actions/cache](https://github.com/actions/cache/issues/31) 
- [Caching build of Docker actions · Issue #81 · actions/cache](https://github.com/actions/cache/issues/81)

**Comment by ankane** [comment]
Hey @Piedone, the install time on Windows isn't great, but I'm not sure of a way to speed it up. Feel free to submit a PR if you find a way / can make it work with caching.
